#page title
page_title                                : "#5000words"                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6478545812                               # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : es                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                         # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/app_logo_5000words.jpg                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : "#5000words"                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Learn vocabulary fast

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Álvaro Jiménez                                
your_link                                 :
your_city                                 :
email_address                             : myemail@gmail.com
facebook_username                         :                                           
instagram_username                        :
twitter_username                          :
github_username                           :
youtube_username                          :
mastodon_link                             :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Learn by Speaking
    description                           : Master vocabulary through voice interactions instead of endless card swiping. Practice pronunciation while learning new words.
    fontawesome_icon_name                 : microphone
    
  - title                                 : Smart Level Testing
    description                           : Start with an adaptive placement test that intelligently determines your current vocabulary level and personalizes your learning path.
    fontawesome_icon_name                 : chart-line

  - title                                 : Focus on Essential Words
    description                           : Learn the 5000 most frequent words that make up 78% of daily conversations. Understand half of your target language with just 500 words.
    fontawesome_icon_name                 : bullseye

  - title                                 : Spaced Repetition
    description                           : Our intelligent algorithm ensures you review words at the optimal time for maximum retention and efficient learning.
    fontawesome_icon_name                 : sync

  - title                                 : 100% Offline Learning
    description                           : Learn anywhere, anytime. No internet connection required for full app functionality.
    fontawesome_icon_name                 : plane
  
  - title                                 : Progress Tracking
    description                           : Monitor your journey with clear statistics showing words To Learn, Learning, and Learned.
    fontawesome_icon_name                 : chart-bar

  - title                                 : Progressive Hints
    description                           : Stuck on a word? Get letter-by-letter hints to help you progress without getting frustrated.
    fontawesome_icon_name                 : lightbulb

  - title                                 : Minimalist Design
    description                           : Clean, distraction-free interface with pure dark mode support for focused learning sessions.
    fontawesome_icon_name                 : moon

  - title                                 : Multiple Languages
    description                           : Currently supporting English and Spanish, with more languages coming soon including French, German, Italian, and more.
    fontawesome_icon_name                 : language



# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.9

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#121212"                                # Changed from "#ffffff" to dark

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"                                # Changed from "#000000" to white
feature_text_color                        : "#a7a7a7"                               # Changed from "#666666" to lighter gray

feature_icons_foreground_color            : "#1d63ea"                               # Kept blue accent
feature_icons_background_color            : "#2d2d2d"                               # Changed from "#e6e6e6" to darker gray

social_icons_foreground_color             : "#a7a7a7"                               # Changed from "#666666" to lighter gray
social_icons_background_color             : "#2d2d2d"                               # Changed from "#e6e6e6" to darker gray

footer_text_color                         : "#a7a7a7"                               # Changed from "#666666" to lighter gray








####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
